dist: trusty
sudo: false
language: php
php:
  - '7.0.26'
  - '7.1.12'
  - '7.2.0'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - npm install -g sloc@latest
  - cp .env.travis .env
  - mysql -u root -e 'create database `docspen-test`;'
  - mysql -u root -e "CREATE USER 'docspen-test'@'localhost' IDENTIFIED BY 'docspen-test';"
  - mysql -u root -e "GRANT ALL ON \`docspen-test\`.* TO 'docspen-test'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist --no-interaction
  - php artisan clear-compiled -n
  - php artisan optimize -n
  - php artisan migrate --force -n --database=mysql_testing
  - php artisan db:seed --force -n --class=DummyContentSeeder --database=mysql_testing

after_failure:
  - cat storage/logs/laravel.log

script:
  - phpunit
  - sloc .